# Generated by Django 3.1 on 2020-08-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
